services:
  api:
    build:
      context: .
      network: host
    command: warehouse-monitoring-api
    restart: unless-stopped
    ports:
      - ${APPLICATION_HOST}:${APPLICATION_PORT}:8000
    env_file:
      .env
    environment:
      POSTGRES_HOST: database
      REDIS_HOST: broker
      CELERY_CONFIG_MODULE: rksi_app.celeryconfig
    depends_on:
      - database
    volumes:
      - type: bind
        source: ${CONFIG_PATH}
        target: /config
        read_only: true
  database:
    image: "postgres:15.2"
    restart: unless-stopped
    env_file:
      .env
    ports:
      - 0.0.0.0:5432:${POSTGRES_PORT}
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
